name: rolling

on:
  pull_request:
    branches:
      - rolling
  push:
    branches:
      - rolling
  schedule:
      - cron: '0 0 * * 6'     
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
      fail-fast: false
    steps:
      - name: Repo checkout
        uses: actions/checkout@v4

      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.7.13
        with:
          required-ros-distributions: rolling

      - name: build and test
        uses: ros-tooling/action-ros-ci@0.4.3
        with:
          package-name:  easynav_indoor_testcase
          target-ros2-distro: rolling
          skip-tests: true
          colcon-defaults: |
            {
              "build": {
                "packages-up-to": true,
                  "mixin": ["coverage-gcc"]
              }
            }
          colcon-mixin-name: coverage-gcc
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml

      - name: Codecov
        uses: codecov/codecov-action@v5.4.0
        with:
          files: ros_ws/lcov/total_coverage.info
          flags: unittests
          name: codecov-umbrella
          # yml: ./codecov.yml
          fail_ci_if_error: false
